---
- name: Set EasyTier download URL
  set_fact:
    easytier_url: "https://github.com/EasyTier/EasyTier/releases/download/{{ easytier_version }}/easytier-linux-{{ ansible_architecture }}-{{ easytier_version }}.zip"
    easytier_dir: "easytier-linux-{{ ansible_architecture }}"

- name: Download EasyTier binary
  get_url:
    url: "{{ easytier_url }}"
    dest: "/tmp/{{ easytier_dir }}.zip"
    mode: '0755'

- name: Extract EasyTier binaries
  unarchive:
    src: "/tmp/{{ easytier_dir }}.zip"
    dest: "/tmp/"
    remote_src: true

- name: Move easytier-core binary to {{ config_dir }}/bin
  copy:
    src: "/tmp/{{ easytier_dir }}/easytier-core"
    dest: "{{ config_dir }}/bin/easytier-core"
    mode: '0755'
    remote_src: true

- name: Move easytier-cli binary to {{ config_dir }}/bin
  copy:
    src: "/tmp/{{ easytier_dir }}/easytier-cli"
    dest: "{{ config_dir }}/bin/easytier-cli"
    mode: '0755'
    remote_src: true
