---
- name: Create EasyTier directory
  file:
    path: "{{ easytier_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set EasyTier download URL
  set_fact:
    easytier_url: "https://github.com/EasyTier/EasyTier/releases/download/{{ easytier_version }}/easytier-linux-{{ ansible_architecture }}-{{ easytier_version }}.zip"
    easytier_temp_dir: "/tmp/easytier-linux-{{ ansible_architecture }}"

- name: Download EasyTier binary
  get_url:
    url: "{{ easytier_url }}"
    dest: "{{ easytier_temp_dir }}.zip"
    mode: '0755'

- name: Extract EasyTier binaries
  unarchive:
    src: "{{ easytier_temp_dir }}.zip"
    dest: "/tmp/"
    remote_src: true

- name: Move easytier-core binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-core"
    dest: "{{ easytier_dir }}/easytier-core"
    mode: '0755'
    remote_src: true

- name: Move easytier-cli binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-cli"
    dest: "{{ easytier_dir }}/easytier-cli"
    mode: '0755'
    remote_src: true

- name: Delete EasyTier downloaded zip file
  file:
    path: "{{ easytier_temp_dir }}.zip"
    state: absent

- name: Delete EasyTier extracted directory
  file:
    path: "{{ easytier_temp_dir }}"
    state: absent

- name: Setup EasyTier service for internal network
  template:
    src: "{{ 'server.service.j2' if reverse else 'client.service.j2' }}"
    dest: "/etc/systemd/system/easytier.service"
  when: inventory_hostname == 'internal-network'

- name: Setup EasyTier service for external network
  template:
    src: "{{ 'client.service.j2' if reverse else 'server.service.j2' }}"
    dest: "/etc/systemd/system/easytier.service"
  when: inventory_hostname == 'external-network'

- name: Enable EasyTier service
  systemd:
    name: easytier
    state: started
    daemon_reload: true
    enabled: true

- name: Restart EasyTier service
  systemd:
    name: easytier
    state: restarted
    daemon_reload: true

- name: Wait for easytier interface to be available
  pause:
    seconds: 10

- name: Apply CAKE qdisc to the easytier interface
  command: "tc qdisc replace dev easytier root cake diffserv4 bandwidth {{ bandwidth }} rtt {{ rtt }}"
