---
- name: Make EasyTier directory
  file:
    path: "{{ easytier_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set EasyTier download URL
  set_fact:
    easytier_url: "https://github.com/EasyTier/EasyTier/releases/download/{{ easytier_version }}/easytier-linux-{{ ansible_architecture }}-{{ easytier_version }}.zip"
    easytier_temp_dir: "/tmp/easytier-linux-{{ ansible_architecture }}"

- name: Download EasyTier binary
  get_url:
    url: "{{ easytier_url }}"
    dest: "{{ easytier_temp_dir }}.zip"
    mode: 0755

- name: Extract EasyTier binaries
  unarchive:
    src: "{{ easytier_temp_dir }}.zip"
    dest: "/tmp/"
    remote_src: true

- name: Move easytier-core binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-core"
    dest: "{{ easytier_dir }}/easytier-core"
    mode: 0755
    remote_src: true

- name: Move easytier-cli binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-cli"
    dest: "{{ easytier_dir }}/easytier-cli"
    mode: 0755
    remote_src: true

- name: Delete EasyTier downloaded zip file
  file:
    path: "{{ easytier_temp_dir }}.zip"
    state: absent
  async: 25
  poll: 0

- name: Delete EasyTier extracted directory
  file:
    path: "{{ easytier_temp_dir }}"
    state: absent
  async: 25
  poll: 0

- name: Determine peer host based on reverse flag
  set_fact:
    peer_host: "{{ hostvars['internal-network'].ansible_host if easytier_reverse else hostvars['external-network'].ansible_host }}"
  delegate_to: localhost
  when: enable_easytier and inventory_hostname == 'internal-network' or inventory_hostname == 'external-network'

- name: Make EasyTier service for internal network
  template:
    src: "{{ 'server.service.j2' if easytier_reverse else 'client.service.j2' }}"
    dest: "/etc/systemd/system/easytier.service"
  when: inventory_hostname == 'internal-network'

- name: Make EasyTier service for external network
  template:
    src: "{{ 'client.service.j2' if easytier_reverse else 'server.service.j2' }}"
    dest: "/etc/systemd/system/easytier.service"
  when: inventory_hostname == 'external-network'

- name: Enable and start EasyTier service
  systemd:
    name: easytier
    state: restarted
    daemon_reload: true
    enabled: true

- name: Make EasyTier TUN setup script
  template:
    src: easytier-tun.sh.j2
    dest: "{{ easytier_dir }}/easytier-tun.sh"
    mode: 0744
    owner: root
    group: root

- name: Make EasyTier TUN setup service
  template:
    src: easytier-tun.service.j2
    dest: /etc/systemd/system/easytier-tun.service
    mode: 0644
    owner: root
    group: root

- name: Enable and start EasyTier TUN setup service
  systemd:
    name: easytier-tun
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: true
