---
- name: Create EasyTier directory
  file:
    path: "{{ easytier_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set EasyTier download URL
  set_fact:
    easytier_url: "https://github.com/EasyTier/EasyTier/releases/download/{{ easytier_version }}/easytier-linux-{{ ansible_architecture }}-{{ easytier_version }}.zip"
    easytier_temp_dir: "/tmp/easytier-linux-{{ ansible_architecture }}"

- name: Download EasyTier binary
  get_url:
    url: "{{ easytier_url }}"
    dest: "{{ easytier_temp_dir }}.zip"
    mode: '0755'

- name: Extract EasyTier binaries
  unarchive:
    src: "{{ easytier_temp_dir }}.zip"
    dest: "/tmp/"
    remote_src: true

- name: Move easytier-core binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-core"
    dest: "{{ easytier_dir }}/easytier-core"
    mode: '0755'
    remote_src: true

- name: Move easytier-cli binary to {{ easytier_dir }}
  copy:
    src: "{{ easytier_temp_dir }}/easytier-cli"
    dest: "{{ easytier_dir }}/easytier-cli"
    mode: '0755'
    remote_src: true

- name: Delete EasyTier downloaded zip file
  file:
    path: "{{ easytier_temp_dir }}.zip"
    state: absent

- name: Delete EasyTier extracted directory
  file:
    path: "{{ easytier_temp_dir }}"
    state: absent
