- name: Restart ssh
  systemd:
    name: ssh
    state: restarted

- name: Restart iptables
  systemd:
    name: iptables
    state: restarted

- name: Restart nftables
  systemd:
    name: nftables
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Reload journald
  systemd:
    name: systemd-journald
    state: reloaded

- name: Reload sysctl
  command: sysctl -p
