---
- name: Set GRUB parameters
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*'
    replace: |
      {% if ansible_processor_vcpus|int > 1 %}
      GRUB_CMDLINE_LINUX_DEFAULT="quiet audit=0 mitigations=off nohz_full=1-{{ ansible_processor_vcpus - 1 }} isolcpus=1-{{ ansible_processor_vcpus - 1 }} rcu_nocbs=1-{{ ansible_processor_vcpus - 1 }} nosoftlockup irqaffinity=0"
      {% else %}
      GRUB_CMDLINE_LINUX_DEFAULT="quiet audit=0 mitigations=off nosoftlockup irqaffinity=0"
      {% endif %}

- name: Update GRUB configuration
  command: update-grub

- name: Reboot the server
  reboot:
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
