---
- name: Install real-time kernel
  apt:
    update_cache: true
    name: "{{ rt_kernel_package }}"
    state: present

- name: Set default kernel to RT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT="1>0"' # grep menuentry /boot/grub/grub.cfg

- name: Optimize kernel
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ ansible_facts['grub_cmdline_linux_default'] | default('') }} preempt=full nohz_full=all threadirqs quiet"'
    backrefs: true

- name: Update GRUB configuration
  command: update-grub

- name: Reboot the system
  reboot:
    msg: "Rebooting to apply the new kernel"
    test_command: uname -r
    reboot_timeout: 600
    pre_reboot_delay: 5
    post_reboot_delay: 30
