---
- name: Disable systemd journal logging
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^#Storage='
    line: 'Storage=none'
    state: present
  ignore_errors: true
  notify:
    - Reload journald

- name: Disable rsyslog service
  systemd:
    name: rsyslog
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable logrotate
  systemd:
    name: logrotate
    state: stopped
    enabled: false
  ignore_errors: true

- name: Disable auditd service
  systemd:
    name: auditd
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove cron daily logrotate
  file:
    path: /etc/cron.daily/logrotate
    state: absent
  ignore_errors: true

