---
- name: Install packages
  import_tasks: packages.yml
  tags: packages

- name: Configure network interfaces
  import_tasks: nic.yml
  tags: nic

- name: Configure logging
  import_tasks: logging.yml
  tags: logging

- name: Change limits.conf
  import_tasks: limits.yml
  tags: hardening

- name: Configure sshd
  import_tasks: hardening.yml
  tags: hardening

- name: Configure firewall
  import_tasks: firewall.yml
  tags: firewall

- name: Confiugre resolved.conf
  import_tasks: resolved.yml
  tags: hardening

- name: Change sysctl.conf
  import_tasks: sysctl.yml
  tags: sysctl

- name: Install RT kernel
  import_tasks: kernel.yml
  tags: rt-kernel
  when: is_rt_kernel_valid
