---
- name: Disable nftables service
  systemd:
    name: nftables
    enabled: false
    state: stopped
  ignore_errors: true

- name: Disable iptables service
  systemd:
    name: iptables
    enabled: false
    state: stopped
  ignore_errors: true

- name: Remove the netfilter modules
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop:
    - nft_compat
    - nfnetlink
    - ipt_REJECT
    - x_tables
    - ip_tables
    - iptable_filter
    - iptable_nat
    - iptable_mangle
    - iptable_raw
    - ip6_tables
    - ip6table_filter
    - ip6table_nat
    - ip6table_mangle
    - ip6table_raw
    - nf_tables
    - nf_tables_set
    - nf_conntrack
    - nf_conntrack_netlink
    - nf_conntrack_ipv4
    - nf_conntrack_ipv6
    - nf_conntrack_ftp
    - nf_conntrack_sip
    - nf_conntrack_tftp
    - nf_nat
    - nf_nat_ipv4
    - nf_nat_ipv6
    - nf_nat_ftp
    - nf_nat_sip
    - nf_nat_tftp
    - nf_reject_ipv4
    - nf_reject_ipv6
    - nf_defrag_ipv4
    - nf_defrag_ipv6
    - nf_log_ipv4
    - nf_log_ipv6
    - nf_log_arp
    - xt_conntrack
    - xt_MASQUERADE
    - xt_mark
    - xt_owner
    - xt_recent
    - xt_limit
    - xt_nat
    - xt_tcpudp
    - xt_state
    - xt_LOG
    - xt_CT
    - xt_multiport
    - xt_comment
    - br_netfilter
  failed_when: false

- name: Blacklist netfilter modules
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disable-netfilter.conf
    content: |
      blacklist ip_tables
      blacklist iptable_filter
      blacklist iptable_nat
      blacklist ip6_tables
      blacklist ip6table_filter
      blacklist ip6table_nat
      blacklist x_tables
      blacklist nf_tables
      blacklist nf_conntrack
      blacklist br_netfilter
      blacklist nft_compat
      blacklist nfnetlink
