---
- name: Add the sch_cake module
  community.general.modprobe:
    name: sch_cake
    state: present

- name: Apply CAKE qdisc to the public interface
  command: "tc qdisc replace dev {{ public_interface }} root cake diffserv4"
  when: public_interface is defined

