---
## supported: nftables, none
firewall: none

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 80
    - 443
    - 2087
    - 2083
    - 2096
  udp_port_access:
    - 443
    - 2087
    - 2083
    - 2096
  trusted_range:
    - 10.44.44.0/24
    - "{{ hostvars['external-network'].ansible_host }}/32"
    - "{{ hostvars['internal-network'].ansible_host }}/32"
