---
## supported: nftables, none
firewall: none

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 8082
    - 8084
  udp_port_access:
    - 8082
    - 8084
  trusted_range:
    - 10.44.44.0/24
    - "{{ hostvars['wormhole'].ansible_host }}/32"
    - "{{ hostvars['stargate'].ansible_host }}/32"
