---
## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: "off"   # TCP Segmentation Offload
gso: "off"   # Generic Segmentation Offload
gro: "off"   # Generic Receive Offload
lro: "off"   # Large Receive Offload

## Ethernet flow control
## https://en.wikipedia.org/wiki/Ethernet_flow_control
autoneg: "off"
rx: "off"
tx: "off"

## Adaptive RX/TX
adaptive_rx: "off"
adaptive_tx: "off"

## RX/TX polling interval
rx_usecs: 0
tx_usecs: 0

## RX/TX queue length
rx_frames: 1
tx_frames: 1

## NAPI
napi_defer_hard_irqs: 1
gro_flush_timeout: 1
threaded_napi: 1
