## basic package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- unzip
- net-tools
- dnsutils
- tcpdump
- ethtool

## monitoring (prometheus)
monitoring: false
node_exporter_listen_address: ":10100"

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: 0.0.0.0
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## firewall system
## supported: nftables, iptables, none
firewall: none

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 8084
    - 8082
  udp_port_access:
    - 8084
    - 8082
  trusted_range:
    - 10.44.44.0/24
    - "{{ hostvars['external-network'].ansible_host }}/32"
    - "{{ hostvars['internal-network'].ansible_host }}/32"

## packet DSCP configuration
## https://en.wikipedia.org/wiki/Differentiated_services
dscp: true

## resolv.conf name servers
dns: 1.1.1.1
dns_fallback: 1.0.0.1
dns_v6: 2606:4700:4700::1111
dns_v6_fallback: 2606:4700:4700::1001

## systemd-resolved configuration
dnssec: allow-downgrade
dns_over_tls: opportunistic

## limit.conf variables
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000

## qdisc configuration
_fq_codel: "fq_codel target 50us interval 500us noecn limit 2048 flows 1024 quantum 1514"
_pfifo: "pfifo limit 2048"

## supported qdisc: noqueue, fq_codel, pfifo
qdisc: noqueue

## NIC configuration
##
## https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt
## https://en.wikipedia.org/wiki/TCP_offload_engine
##
tso: "off"   # TCP Segmentation Offload
gso: "off"   # Generic Segmentation Offload
gro: "off"   # Generic Receive Offload
lro: "off"   # Large Receive Offload

## Ethernet flow control
## https://en.wikipedia.org/wiki/Ethernet_flow_control
autoneg: "off"
rx: "off"
tx: "off"

## Adaptive RX/TX
adaptive_rx: "off"
adaptive_tx: "off"

## RX/TX polling interval
rx_usecs: 0
tx_usecs: 0

## RX/TX queue length
rx_frames: 1
tx_frames: 1

## NAPI defer hard IRQ
napi_defer: 1

## sysctl configuration variables
sysctl_config:
  net.core.default_qdisc: noqueue
  net.core.somaxconn: 4096
  net.core.netdev_max_backlog: 10000
  net.unix.max_dgram_qlen: 4096
  net.core.busy_read: 250
  net.core.busy_poll: 250
  net.core.netdev_budget: 600
  net.core.netdev_budget_usecs: 400
  net.core.dev_weight: 128
  net.core.dev_weight_rx_bias: 1
  net.core.dev_weight_tx_bias: 1
  net.core.flow_limit_table_len: 4096
  net.core.flow_limit_cpu_bitmap: 0
  net.core.netdev_tstamp_prequeue: 0
  net.core.rmem_default: 1048576
  net.core.wmem_default: 1048576
  net.core.rmem_max: 2097152
  net.core.wmem_max: 2097152
  net.core.optmem_max: 65536
  net.ipv4.tcp_no_metrics_save: 1
  net.ipv4.tcp_fin_timeout: 10
  net.ipv4.tcp_keepalive_time: 120
  net.ipv4.tcp_ecn: 0
  net.ipv4.tcp_sack: 0
  net.ipv4.tcp_mtu_probing: 0
  net.ipv4.tcp_timestamps: 0
  net.ipv4.tcp_keepalive_intvl: 20
  net.ipv4.tcp_keepalive_probes: 3
  net.ipv4.tcp_max_orphans: 2048
  net.ipv4.tcp_retries2: 3
  net.ipv4.tcp_synack_retries: 2
  net.ipv4.tcp_window_scaling: 1
  net.ipv4.tcp_slow_start_after_idle: 1
  net.ipv4.tcp_max_tw_buckets: 2048
  net.ipv4.tcp_syncookies: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_max_syn_backlog: 4096
  net.ipv4.tcp_rmem: "4096 87380 1048576"
  net.ipv4.tcp_wmem: "4096 16384 1048576"
  net.ipv4.tcp_low_latency: 1
  net.ipv4.tcp_fastopen: 3
  net.ipv4.tcp_congestion_control: cubic
  net.ipv4.udp_rmem_min: 1048576
  net.ipv4.udp_wmem_min: 1048576
  net.ipv4.udp_l3mdev_accept: 1
  net.ipv4.ip_default_ttl: 64
  net.ipv4.ip_early_demux: 1
  net.ipv4.ip_forward: 1
  net.ipv4.conf.all.forwarding: 1
  net.ipv6.conf.all.forwarding: 1
  net.ipv4.conf.default.rp_filter: 0
  net.ipv4.conf.all.rp_filter: 0
  net.ipv4.icmp_echo_ignore_all: 1
  fs.file-max: 2097152
  vm.max_map_count: 262144
  vm.swappiness: 0
  vm.dirty_ratio: 5
  vm.dirty_background_ratio: 5
  vm.compaction_proactiveness: 0
  net.netfilter.nf_conntrack_max: 262144
  net.netfilter.nf_conntrack_tcp_timeout_established: 900
  net.netfilter.nf_conntrack_tcp_timeout_close_wait: 10
  net.netfilter.nf_conntrack_tcp_timeout_syn_recv: 30
  kernel.printk: "3 4 1 3"
