---
- name: Enable easytier
  systemd:
    name: easytier
    state: start
    daemon_reload: true
    enabled: true
  ignore_errors: true

- name: Enable easytier-tun
  systemd:
    name: easytier-tun
    state: restarted
    daemon_reload: true
    enabled: true
  ignore_errors: true
