---
- name: Setup SIT (6to4) tunnel on wormhole
  shell: |
    ip tunnel add {{ sit_dev }} mode sit remote {{ hostvars['stargate'].ansible_host }} local {{ hostvars['wormhole'].ansible_host }} ttl {{ sit_ttl }}
    ip addr replace {{ sit_local_ipv6 }}{{ sit_netmask }} dev {{ sit_dev }}
    ip link set dev {{ sit_dev }} mtu {{ sit_mtu }}
    ip link set {{ sit_dev }} up
    ip route replace {{ sit_remote_ipv6 }}{{ sit_netmask }} dev {{ sit_dev }}
  args:
    executable: /bin/bash
  ignore_errors: true
  when: inventory_hostname == 'wormhole'

- name: Setup SIT (6to4) tunnel on stargate
  shell: |
    ip tunnel add {{ sit_dev }} mode sit remote {{ hostvars['wormhole'].ansible_host }} local {{ hostvars['stargate'].ansible_host }} ttl {{ sit_ttl }}
    ip addr replace {{ sit_remote_ipv6 }}{{ sit_netmask }} dev {{ sit_dev }}
    ip link set dev {{ sit_dev }} mtu {{ sit_mtu }}
    ip link set {{ sit_dev }} up
    ip route replace {{ sit_local_ipv6 }}{{ sit_netmask }} dev {{ sit_dev }}
  args:
    executable: /bin/bash
  ignore_errors: true
  when: inventory_hostname == 'stargate'
