---
- name: Create Xray directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ xray_dir }}"
    - /etc/systemd/system/xray@.service.d
    - /etc/systemd/system/xray.service.d
    - /var/log/xray

- name: Download Xray Linux X86_64|amd64 binary
  get_url:
    url: "https://github.com/XTLS/Xray-core/releases/download/{{ xray_version }}/Xray-linux-64.zip"
    dest: "/tmp/Xray-linux-64.zip"
    mode: 0644

- name: Extract Xray binary
  unarchive:
    src: "/tmp/Xray-linux-64.zip"
    dest: "{{ xray_dir }}"
    remote_src: true

- name: Delete Xray downloaded zip file
  file:
    path: "/tmp/Xray-linux-64.zip"
    state: absent

- name: Create Xray systemd service
  template:
    src: xray.service.j2
    dest: /etc/systemd/system/xray.service
    owner: root
    group: root
    mode: 0644

- name: Copy Xray default config
  copy:
    src: files/default.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: 0644
  notify:
    - Enable xray

- name: Check if wormhole.json exists
  become: false
  stat:
    path: "{{ role_path }}/files/wormhole.json"
  register: wormhole_config
  delegate_to: localhost

- name: Check if stargate.json exists
  become: false
  stat:
    path: "{{ role_path }}/files/stargate.json"
  register: stargate_config
  delegate_to: localhost

- name: Copy Xray custom config to wormhole
  copy:
    src: files/wormhole.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: 0644
  when: wormhole_config.stat.exists and inventory_hostname == 'wormhole'
  notify:
    - Restart xray

- name: Copy Xray custom config to stargate
  copy:
    src: files/stargate.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: 0644
  when: stargate_config.stat.exists and inventory_hostname == 'stargate'
  notify:
    - Restart xray
