---
- name: Create Xray directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ xray_dir }}"
    - /etc/systemd/system/xray@.service.d
    - /etc/systemd/system/xray.service.d
    - /var/log/xray

- name: Download Xray Linux X86_64|amd64 binary
  get_url:
    url: "https://github.com/XTLS/Xray-core/releases/download/{{ xray_version }}/Xray-linux-64.zip"
    dest: "/tmp/Xray-linux-64.zip"
    mode: '0755'

- name: Extract Xray binary
  unarchive:
    src: "/tmp/Xray-linux-64.zip"
    dest: "{{ xray_dir }}"
    remote_src: true

- name: Delete Xray downloaded zip file
  file:
    path: "/tmp/Xray-linux-64.zip"
    state: absent

- name: Create Xray systemd service
  template:
    src: xray.service.j2
    dest: /etc/systemd/system/xray.service
    owner: root
    group: root
    mode: '0644'

- name: Copy Xray default config
  copy:
    src: files/default.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: '0744'

- name: Enable Xray service
  systemd:
    name: xray
    state: started
    daemon_reload: true
    enabled: true

- name: Check if internal.json exists
  become: false
  stat:
    path: "{{ role_path }}/files/client.json"
  register: client_config_file
  delegate_to: localhost

- name: Check if external.json exists
  become: false
  stat:
    path: "{{ role_path }}/files/server.json"
  register: server_config_file
  delegate_to: localhost

- name: Copy Xray custom config to internal network
  copy:
    src: files/internal.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: "0644"
  when: server_config_file.stat.exists and inventory_hostname == 'internal-network'

- name: Copy Xray custom config to external network
  copy:
    src: files/external.json
    dest: "{{ xray_dir }}/config.json"
    owner: root
    group: root
    mode: "0644"
  when: server_config_file.stat.exists and inventory_hostname == 'external-network'

- name: Restart Xray service
  systemd:
    name: xray
    state: restarted
