---
- name: Create TinyFEC directory
  file:
    path: "{{ tinyfec_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy TinyFEC binary to {{ tinyfec_dir }}
  copy:
    src: files/tinyfec
    dest: "{{ tinyfec_dir }}"
    owner: root
    group: root
    mode: '0755'

- name: Setup TinyFEC service for internal network
  template:
    src: "{{ 'server.service.j2' if reverse else 'client.service.j2' }}"
    dest: "/etc/systemd/system/tinyfec.service"
  when: "'internal-network' in group_names"

- name: Setup TinyFEC service for external network
  template:
    src: "{{ 'client.service.j2' if reverse else 'server.service.j2' }}"
    dest: "/etc/systemd/system/tinyfec.service"
  when: "'external-network' in group_names"

- name: Enable TinyFEC service
  systemd:
    name: tinyfec
    state: started
    daemon_reload: true
    enabled: true

- name: Restart TinyFEC service
  systemd:
    name: tinyfec
    state: restarted
    daemon_reload: true
