---
- name: Create EasyTier systemd service
  template:
    src: easytier.service.j2
    dest: /etc/systemd/system/easytier.service
    owner: root
    group: root
    mode: '0644'

- name: Enable EasyTier service
  systemd:
    name: easytier
    state: started
    daemon_reload: true
    enabled: true

- name: Restart EasyTier service
  systemd:
    name: easytier
    state: restarted
    daemon_reload: true
