---
- name: Create Nomad EasyTier systemd service
  template:
    src: easytier.service.j2
    dest: /etc/systemd/system/nomad-easytier.service
    owner: root
    group: root
    mode: '0644'

- name: Enable Nomad EasyTier service
  systemd:
    name: nomad-easytier
    state: started
    daemon_reload: true
    enabled: true

- name: Restart Nomad EasyTier service
  systemd:
    name: nomad-easytier
    state: restarted
    daemon_reload: true
