---
- name: Create TinyFEC systemd service
  template:
    src: tinyfec.service.j2
    dest: /etc/systemd/system/tinyfec.service
    owner: root
    group: root
    mode: '0644'

- name: Enable TinyFEC service
  systemd:
    name: tinyfec
    state: started
    daemon_reload: true
    enabled: true

- name: Restart TinyFEC service
  systemd:
    name: tinyfec
    state: restarted
    daemon_reload: true
