---
- name: Install basic tools
  apt:
    update_cache: yes
    name:
      - curl
      - wget
      - vim
      - htop
      - ca-certificates
      - sqlite3
      - iptables-persistent
    state: present

- name: Create Nomad config directory
  file:
    path: "{{ config_dir }}/bin"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Nomad binary to servers
  copy:
    src: files/nomad_amd64
    dest: "{{ config_dir }}/bin/nomad_amd64"
    owner: root
    group: root
    mode: '0755'
