---
- name: Configure EasyTier
  import_tasks: easytier.yml
  when: enable_easytier
  tags: easytier

- name: Configure TinyFEC
  import_tasks: tinyfec.yml
  when: enable_tinyfec
  tags: tinyfec

- name: Configure Xray
  import_tasks: xray.yml
  when: enable_xray
  tags: xray
