---
- name: Preparing tasks for every playbooks
  import_playbook: preparing.yml

- hosts: internal-network
  become: true
  roles:
    - { role: ../roles/easytier, tags: easytier, when: enable_easytier }
    - { role: ../roles/tinyfec, tags: tinyfec, when: enable_tinyfec }
    - { role: ../roles/client, tags: client }
