---
- name: Set RT kernel package name dynamically
  hosts: all
  set_fact:
    rt_kernel_package: "linux-image-rt-{{ ansible_architecture | regex_replace('x86_64', 'amd64') | regex_replace('aarch64', 'arm64') | default('unsupported') }}"
    is_rt_kernel_valid: "{{ rt_kernel_package != 'unsupported' }}"
  when: ansible_distribution == "Debian"

- name: Apply optimizations and hardening
  hosts: all
  become: true
  roles:
    - { role: ../roles/preparing, tags: preparing }
