---
- name: Setup tunnels
  hosts: internal-network,external-network
  become: true
  roles:
    - { role: ../roles/easytier, tags: easytier, when: enable_easytier }
    - { role: ../roles/hysteria, tags: hysteria, when: enable_hysteria }
    - { role: ../roles/sit, tags: sit, when: enable_sit }
