---
- name: Configure tunnels
  hosts: internal-network,external-network
  become: true
  roles:
    - { role: ../roles/easytier, tags: easytier, when: enable_easytier }
    - { role: ../roles/sit, tags: sit, when: enable_sit }
