---
- name: Preparing tasks for every playbooks
  import_playbook: preparing.yml

- name: Gathering facts
  import_playbook: facts.yml

- hosts: internal-network,external-network
  become: true
  roles:
    - { role: ../roles/easytier, tags: easytier, when: enable_easytier }
    - { role: ../roles/tinyfec, tags: tinyfec, when: enable_tinyfec }

- hosts: all
  become: true
  roles:
    - { role: ../roles/xray, tags: xray, when: enable_xray }
    - { role: ../roles/xui, tags: xui, when: enable_xui }
