---
- name: Common tasks for every playbooks
  import_playbook: common.yml

- hosts: external-network
  become: true
  roles:
    - ../roles/server

- hosts: internal-network
  become: true
  roles:
    - ../roles/client
