---
- name: Preparing tasks for every playbooks
  import_playbook: preparing.yml

- hosts: all
  become: true
  roles:
    - { role: ../roles/xui, tags: xui, when: enable_xui }

- hosts: external-network
  become: true
  roles:
    - { role: ../roles/server, tags: server }

- hosts: internal-network
  become: true
  roles:
    - { role: ../roles/client, tags: client }
